from enum import StrEnum


REQUEST_ID_HEADER = "X-Request-ID"
UNKNOWN_REQUEST_ID = "unknown"

DEFAULT_SUCCESS_MESSAGE = "Operation completed successfully"
VALIDATION_ERROR_MESSAGE = "Validation failed"
DEFAULT_HTTP_ERROR_MESSAGE = "Request failed"
INTERNAL_ERROR_MESSAGE = "An unexpected error occurred"


class ApiErrorCode(StrEnum):
    BAD_REQUEST = "BAD_REQUEST"
    AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    CONFLICT = "CONFLICT"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    UNPROCESSABLE_ENTITY = "UNPROCESSABLE_ENTITY"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    HTTP_ERROR = "HTTP_ERROR"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
